name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Run syntax check
        run: |
          poetry run python -m py_compile src/bot.py

      - name: Test imports and basic initialization
        run: |
          poetry run python -c "
          import sys
          import discord
          import aiohttp
          import asyncio
          from datetime import datetime, timedelta
          from discord.ext import commands, tasks
          from dotenv import load_dotenv
          print('All imports successful!')
          
          # Test bot creation
          intents = discord.Intents.default()
          intents.message_content = True
          intents.members = True
          bot = commands.Bot(command_prefix='!', intents=intents)
          print('Bot creation successful!')
          
          # Test aiohttp session creation
          async def test_session():
              async with aiohttp.ClientSession() as session:
                  print('Session creation successful!')
          
          asyncio.run(test_session())
          print('All basic initialization tests passed!')
          "

      - name: Run pytest
        run: |
          poetry add pytest pytest-asyncio
          poetry run pytest tests/ -v